// =========================================================================
// THE COVERAGE WONK — review index data
// One entry per coverage file. Drives the home page list + filter/sort.
// Full coverage prose lives in /reviews/<slug>.html
// =========================================================================
window.COVERAGE_DATA = [
  { file: "CW-001", slug: "chinatown",                   title: "Chinatown",                          year: 1974, decade: "1970s", director: "Roman Polanski",        writer: "Robert Towne",           genre: "Period Crime / Mystery",          pages: 124, station: "PASS",     score: 4.0 },
  { file: "CW-002", slug: "network",                     title: "Network",                            year: 1976, decade: "1970s", director: "Sidney Lumet",          writer: "Paddy Chayefsky",        genre: "Satire / Media Drama",            pages: 118, station: "PASS",     score: 3.7 },
  { file: "CW-003", slug: "midnight-run",                title: "Midnight Run",                       year: 1988, decade: "1980s", director: "Martin Brest",          writer: "George Gallo",           genre: "Action / Buddy Comedy",           pages: 132, station: "PASS",     score: 5.0 },
  { file: "CW-004", slug: "casablanca",                  title: "Casablanca",                         year: 1942, decade: "1940s", director: "Michael Curtiz",        writer: "Epstein / Epstein / Koch", genre: "Period Drama / Wartime Romance",  pages: 114, station: "PASS",     score: 4.7 },
  { file: "CW-005", slug: "2001-a-space-odyssey",        title: "2001: A Space Odyssey",              year: 1968, decade: "1960s", director: "Stanley Kubrick",       writer: "Kubrick / Clarke",       genre: "Science Fiction / Procedural",    pages: 98,  station: "PASS",     score: 3.0 },
  { file: "CW-006", slug: "dr-strangelove",              title: "Dr. Strangelove",                    year: 1964, decade: "1960s", director: "Stanley Kubrick",       writer: "Kubrick / Southern / George", genre: "Satire / Cold War Thriller", pages: 104, station: "PASS",     score: 5.8 },
  { file: "CW-007", slug: "all-the-presidents-men",      title: "All the President's Men",            year: 1976, decade: "1970s", director: "Alan J. Pakula",        writer: "William Goldman",        genre: "Investigative Thriller / Procedural", pages: 121, station: "PASS", score: 4.4 },
  { file: "CW-008", slug: "a-few-good-men",              title: "A Few Good Men",                     year: 1992, decade: "1990s", director: "Rob Reiner",            writer: "Aaron Sorkin",           genre: "Legal Drama / Military Procedural", pages: 122, station: "PASS",  score: 5.1 },
  { file: "CW-009", slug: "phantom-thread",              title: "Phantom Thread",                     year: 2017, decade: "2010s", director: "Paul Thomas Anderson",  writer: "Paul Thomas Anderson",   genre: "Period Drama / Psychological Romance", pages: 116, station: "PASS", score: 4.8 },
  { file: "CW-010", slug: "ad-astra",                    title: "Ad Astra",                           year: 2019, decade: "2010s", director: "James Gray",            writer: "Gray / Gross",           genre: "Sci-Fi / Psychological Drama",    pages: 115, station: "PASS",     score: 3.4 },
  { file: "CW-011", slug: "pulp-fiction",                title: "Pulp Fiction",                       year: 1994, decade: "1990s", director: "Quentin Tarantino",     writer: "Quentin Tarantino",      genre: "Anthological Crime / Neo-Noir",   pages: 159, station: "PASS",     score: 4.3 },
  { file: "CW-012", slug: "magnolia",                    title: "Magnolia",                           year: 1999, decade: "1990s", director: "Paul Thomas Anderson",  writer: "Paul Thomas Anderson",   genre: "Ensemble Drama",                  pages: 182, station: "PASS",     score: 3.2 },
  { file: "CW-013", slug: "the-social-network",          title: "The Social Network",                 year: 2010, decade: "2010s", director: "David Fincher",         writer: "Aaron Sorkin",           genre: "Legal Drama / Corporate Biography", pages: 162, station: "PASS",   score: 3.9 },
  { file: "CW-014", slug: "i-melt-with-you",             title: "I Melt With You",                    year: 2011, decade: "2010s", director: "Mark Pellington",       writer: "Glenn Porter",           genre: "Psychological Drama / Avant-Garde Thriller", pages: 106, station: "CONSIDER", score: 8.1 },
  { file: "CW-015", slug: "ballerina",                   title: "Ballerina",                          year: 2025, decade: "2020s", director: "Len Wiseman",           writer: "Shay Hatten",            genre: "Action / Hyper-Stylized Revenge Thriller", pages: 99, station: "CONSIDER", score: 9.1 },
  { file: "CW-016", slug: "parasite",                    title: "Parasite",                           year: 2019, decade: "2010s", director: "Bong Joon-ho",          writer: "Bong / Han",             genre: "Domestic Thriller / Satire",      pages: 141, station: "PASS",     score: 4.2 },
  { file: "CW-017", slug: "manchester-by-the-sea",       title: "Manchester by the Sea",              year: 2016, decade: "2010s", director: "Kenneth Lonergan",      writer: "Kenneth Lonergan",       genre: "Melodrama / Character Study",     pages: 126, station: "PASS",     score: 3.1 },
  { file: "CW-018", slug: "whiplash",                    title: "Whiplash",                           year: 2014, decade: "2010s", director: "Damien Chazelle",       writer: "Damien Chazelle",        genre: "Psychological Drama / Workplace Thriller", pages: 103, station: "PASS", score: 5.5 },
  { file: "CW-019", slug: "birdman",                     title: "Birdman",                            year: 2014, decade: "2010s", director: "Alejandro G. Iñárritu", writer: "Iñárritu / Giacobone / Bo / Dinelaris", genre: "Satire / Backstage Comedy-Drama", pages: 118, station: "PASS", score: 3.8 },
  { file: "CW-020", slug: "moonlight",                   title: "Moonlight",                          year: 2016, decade: "2010s", director: "Barry Jenkins",         writer: "Barry Jenkins",          genre: "Melodrama / Coming-of-Age",       pages: 101, station: "PASS",     score: 3.4 },
  { file: "CW-021", slug: "spotlight",                   title: "Spotlight",                          year: 2015, decade: "2010s", director: "Tom McCarthy",          writer: "McCarthy / Singer",      genre: "Investigative Drama / Procedural", pages: 119, station: "PASS",    score: 4.6 },
  { file: "CW-022", slug: "green-book",                  title: "Green Book",                         year: 2018, decade: "2010s", director: "Peter Farrelly",        writer: "Vallelonga / Currie / Farrelly", genre: "Buddy Comedy / Road-Trip Melodrama", pages: 114, station: "PASS", score: 5.3 },
  { file: "CW-023", slug: "the-shape-of-water",          title: "The Shape of Water",                 year: 2017, decade: "2010s", director: "Guillermo del Toro",    writer: "del Toro / Taylor",      genre: "Fantasy / Period Melodrama",      pages: 121, station: "PASS",     score: 4.1 },
  { file: "CW-024", slug: "everything-everywhere-all-at-once", title: "Everything Everywhere All at Once", year: 2022, decade: "2020s", director: "Daniels", writer: "Daniels", genre: "Sci-Fi / Absurdist Action-Comedy", pages: 148, station: "CONSIDER", score: 6.2 },
  { file: "CW-025", slug: "arrival",              title: "Arrival",                 year: 2016, decade: "2010s", director: "Denis Villeneuve",    writer: "Eric Heisserer",          genre: "Sci-Fi / Linguistic Procedural",     pages: 116, station: "PASS", score: 4.3 },
  { file: "CW-026", slug: "coda",                 title: "CODA",                    year: 2021, decade: "2020s", director: "Siân Heder",          writer: "Siân Heder",              genre: "Coming-of-Age / Domestic Drama",     pages: 111, station: "PASS", score: 3.5 },
  { file: "CW-027", slug: "the-zone-of-interest", title: "The Zone of Interest",    year: 2023, decade: "2020s", director: "Jonathan Glazer",     writer: "Jonathan Glazer",         genre: "Historical Drama / Avant-Garde",     pages: 94,  station: "PASS", score: 2.8 },
  { file: "CW-028", slug: "anatomy-of-a-fall",    title: "Anatomy of a Fall",       year: 2023, decade: "2020s", director: "Justine Triet",       writer: "Triet & Harari",          genre: "Legal Drama / Psychological Thriller", pages: 152, station: "PASS", score: 4.1 },
  { file: "CW-029", slug: "oppenheimer",          title: "Oppenheimer",             year: 2023, decade: "2020s", director: "Christopher Nolan",   writer: "Christopher Nolan",       genre: "Historical Drama / Biopic",          pages: 180, station: "PASS", score: 4.2 },
  { file: "CW-030", slug: "ordinary-people",      title: "Ordinary People",         year: 1980, decade: "1980s", director: "Robert Redford",      writer: "Alvin Sargent",           genre: "Domestic Melodrama",                 pages: 118, station: "PASS",     score: 3.4 },
  { file: "CW-031", slug: "chariots-of-fire",     title: "Chariots of Fire",        year: 1981, decade: "1980s", director: "Hugh Hudson",         writer: "Colin Welland",           genre: "Sports Drama / Period Biopic",       pages: 121, station: "PASS",     score: 3.8 },
  { file: "CW-032", slug: "gandhi",               title: "Gandhi",                  year: 1982, decade: "1980s", director: "Richard Attenborough", writer: "John Briley",             genre: "Epic Historical Biography",          pages: 178, station: "PASS",     score: 3.5 },
  { file: "CW-033", slug: "amadeus",              title: "Amadeus",                 year: 1984, decade: "1980s", director: "Miloš Forman",        writer: "Peter Shaffer",           genre: "Period Drama / Musical Biopic",      pages: 158, station: "PASS",     score: 4.5 },
  { file: "CW-034", slug: "out-of-africa",        title: "Out of Africa",           year: 1985, decade: "1980s", director: "Sydney Pollack",      writer: "Kurt Luedtke",            genre: "Period Melodrama / Romance",         pages: 154, station: "PASS",     score: 3.2 },
  { file: "CW-035", slug: "platoon",              title: "Platoon",                 year: 1986, decade: "1980s", director: "Oliver Stone",        writer: "Oliver Stone",            genre: "Military Action / Vietnam War Drama", pages: 114, station: "CONSIDER", score: 7.1 },
  { file: "CW-036", slug: "rain-man",             title: "Rain Man",                year: 1988, decade: "1980s", director: "Barry Levinson",      writer: "Bass & Morrow",           genre: "Drama / Road-Trip Melodrama",        pages: 122, station: "CONSIDER", score: 7.4 },
  { file: "CW-037", slug: "taxi-driver",          title: "Taxi Driver",             year: 1976, decade: "1970s", director: "Martin Scorsese",     writer: "Paul Schrader",           genre: "Psychological Thriller / Neo-Noir", pages: 114, station: "PASS", score: 0.9 },
  { file: "CW-038", slug: "the-goonies",          title: "The Goonies",             year: 1985, decade: "1980s", director: "Richard Donner",      writer: "Columbus & Spielberg",    genre: "Action-Adventure / Four-Quadrant Family", pages: 112, station: "CONSIDER", score: 9.4 },
  { file: "CW-039", slug: "the-incredibles",      title: "The Incredibles",         year: 2004, decade: "2000s", director: "Brad Bird",           writer: "Brad Bird",               genre: "Action-Adventure / Animated Four-Quadrant", pages: 114, station: "CONSIDER", score: 9.0 },
  { file: "CW-040", slug: "aliens",               title: "Aliens",                  year: 1986, decade: "1980s", director: "James Cameron",       writer: "James Cameron",           genre: "Sci-Fi / Action-Thriller",            pages: 118, station: "CONSIDER", score: 9.3 },
  { file: "CW-041", slug: "mad-max-fury-road",    title: "Mad Max: Fury Road",      year: 2015, decade: "2010s", director: "George Miller",       writer: "Miller, McCarthy & Lathouris", genre: "High-Concept Action / Post-Apocalyptic Thriller", pages: 102, station: "CONSIDER", score: 9.3 },
  { file: "CW-042", slug: "winter-soldier",       title: "Captain America: The Winter Soldier", year: 2014, decade: "2010s", director: "Russo Brothers", writer: "Markus & McFeely",        genre: "Political Spy Thriller / Superhero Action", pages: 120, station: "CONSIDER", score: 8.5 },
  { file: "CW-043", slug: "the-princess-bride",   title: "The Princess Bride",      year: 1987, decade: "1980s", director: "Rob Reiner",          writer: "William Goldman",         genre: "Fantasy / Adventure Comedy",          pages: 106, station: "CONSIDER", score: 8.8 },
  { file: "CW-044", slug: "frances-ha",           title: "Frances Ha",              year: 2012, decade: "2010s", director: "Noah Baumbach",       writer: "Baumbach & Gerwig",       genre: "Mumblecore / Independent Dramedy",    pages: 104, station: "PASS",     score: 2.9 },
  { file: "CW-045", slug: "the-hateful-eight",    title: "The Hateful Eight",       year: 2015, decade: "2010s", director: "Quentin Tarantino",   writer: "Quentin Tarantino",       genre: "Period Mystery / Revisionist Western", pages: 146, station: "PASS",     score: 0.8 },
  { file: "CW-046", slug: "the-fifth-element",    title: "The Fifth Element",       year: 1997, decade: "1990s", director: "Luc Besson",          writer: "Besson & Kamen",          genre: "Sci-Fi / Action",                     pages: 118, station: "PASS",     score: 0.4 },
  { file: "CW-047", slug: "bull-durham",          title: "Bull Durham",             year: 1988, decade: "1980s", director: "Ron Shelton",         writer: "Ron Shelton",             genre: "Sports Comedy / Romantic Drama",      pages: 116, station: "CONSIDER", score: 8.6 },
  { file: "CW-048", slug: "killing-of-a-sacred-deer", title: "The Killing of a Sacred Deer", year: 2017, decade: "2010s", director: "Yorgos Lanthimos", writer: "Lanthimos & Filippou", genre: "Psychological Horror / Surrealist Thriller", pages: 110, station: "PASS", score: 3.5 },
  { file: "CW-049", slug: "hereditary",           title: "Hereditary",              year: 2018, decade: "2010s", director: "Ari Aster",           writer: "Ari Aster",               genre: "Supernatural Horror / Family Melodrama", pages: 116, station: "PASS", score: 2.2 },
  { file: "CW-050", slug: "beau-is-afraid",       title: "Beau Is Afraid",          year: 2023, decade: "2020s", director: "Ari Aster",           writer: "Ari Aster",               genre: "Surrealist Comedy / Existential Drama", pages: 179, station: "PASS", score: 1.6 },
  { file: "CW-051", slug: "three-billboards",     title: "Three Billboards Outside Ebbing, Missouri", year: 2017, decade: "2010s", director: "Martin McDonagh", writer: "Martin McDonagh", genre: "Dark Comedy / Crime Drama", pages: 112, station: "PASS", score: 1.1 },
  { file: "CW-052", slug: "materialists",         title: "Materialists",            year: 2025, decade: "2020s", director: "Celine Song",         writer: "Celine Song",             genre: "Romantic Comedy / Modern Relationship Drama", pages: 106, station: "PASS", score: 3.9 }
];

// ----- MOST READ · PAST 30 DAYS -----
// Edit this array to reorder the trending sidebar widget on the home page.
// To shuffle the list, just rearrange the entries. Fake read counts.
window.MOST_READ = [
  { slug: "chinatown",                          reads: 14729 },
  { slug: "taxi-driver",                        reads: 13288 },
  { slug: "the-zone-of-interest",               reads: 12482 },
  { slug: "pulp-fiction",                       reads: 11317 },
  { slug: "ballerina",                          reads: 9846  },
  { slug: "parasite",                           reads: 8902  },
  { slug: "oppenheimer",                        reads: 7531  },
  { slug: "whiplash",                           reads: 7124  },
  { slug: "the-social-network",                 reads: 6892  },
  { slug: "magnolia",                           reads: 6210  }
];
